# Introduction

My aim is to develop a "bioelectronic nose", a bio-inspired sensor device which couples sensitive biological elements with an electronic transducer [@Lee2010; @Dung2018; @Moon2020], for the detection of VOCs in the vapour phase, using *Drosophila melanogaster* insect odorant receptors (iORs) as my sensitive biological component and a carbon nanotube- or graphene-based field effect transistor (CNTFET or GFET) as my transducer element. I have, in collaboration with others, developed a odorant sensing apparatus to achieve this aim. After testing my iOR-functionalised CNTFETs and GFETs (iOR-FETs) in the liquid phase by building on previous findings within our research group [@Murugathas2019b, @Murugathas2020], I will investigate different approaches for odorant sensing in this apparatus.  In the first stage of my PhD, I will detect VOCs individually, and once this is accomplished, I will develop a multiplexed device able to detect mixtures of VOCs.
    
There has been a significant amount of work done towards creating bioelectronic noses over the last twenty years. This is largely due to their promisingly high level of sensitivity and specificity in real-time in the gas phase, with the ability to signal the presence of volatile organic compound (VOC) traces at lower concentrations than traditional chemical sensors or the human nose in a timescale of seconds [@Lee2010; @Moon2020; @Terutsuki2020]. The implications of successful development of a portable and robust bioelectronic nose are significant and varied. Applications could be found in high-importance fields such as biosecurity, medicine, environmental protection and food or water safety [@Dung2018; @Arakawa2019; @Yang2017; @Son2017]. It has been demonstrated that it is possible to detect invasive brown marmorated stinkbugs based on their VOC trace [@Moser2020]. A bioelectronic nose could potentially accomplish this task far more cheaply and efficiently than trained sniffer dogs.
    
As well as a variety of practical applications, development of a bioelectronic nose may give us a greater understanding of the mechanisms underlying insect olfaction, as well as novel understandings of the transducer devices used to register the electronic response to VOCs [@Lee2010]. The transduction mechanism of nanomaterial-based iOR sensors is still unknown, and I hope to shed further light on the biological and electronic processes underpinning this mechanism [@Murugathas2020; @Khadka2019].  