---
keep-tex: true
format: pdf
---

# Carbon Nanotube and Graphene Field-Effect Transistors as Biosensor Platforms

## Carbon Nanotube Networks & Graphene as Biosensing Transducers {#sec-biosensing-transducers}

As carbon nanotubes and graphene are highly sensitive substances and are easily functionalised with biomaterials, they make an ideal platform for biosensing [@Battie2010; @Ohno2010;  @Benlikaya2019; @Goodwin2021].

## Odorant Receptors {#sec-odorant-receptors}

### *In Vivo* Structure and Function

### Artificial Membranes {#sec-artificial-membranes}



## Odorant Receptor Carbon Nanotube and Graphene Biosensors

### Sensor Types {#sec-sensor-types}

\newpage
\KOMAoptions{paper=landscape,pagesize}

```{r warning=FALSE}
#| label: tbl-or-biosensors
#| tbl-cap: Summary of past fabrication methods for odorant receptor-functionalised carbon nanotube and graphene biosensors. GA = glutaraldehyde, DAN = 1,5-diaminonaphthalene, DMT-MM = 4-(4,6-dimethoxy-1,3,5-triazin-2-yl)-4 methylmorpholinium chloride, NTA = nitrilotriacetic acid, PDL = poly-D-lysine, Ab = Antibody fragments, CNTFET = carbon nanotube field-effect transistor, GFET = graphene field-effect transistor.

knitr::opts_chunk$set(echo = FALSE)
library(knitr)

or_table <- read.csv("tables/ch3/OR_biosensors.csv", sep=",")
or_table <- or_table[rowSums(is.na(or_table)) == 0,]

knitr::kable(or_table, 
            col.names = c("Attachment",
                           "Attachment Method",
                           "References",
                           "Transducer",
                           "OR Type",
                           "OR Format",
                           "LOD"), format = "simple") 
    
```

\newpage
\KOMAoptions{paper=portrait,pagesize}


### Sensor Functionalisation

### Sensing Methods {#sec-biosensor-methods}

#### Aqueous Environment {.unnumbered}

#### Vapour Environment {.unnumbered}

In 2000, Kong et al. found that the resistance over a single CNT channel was modified when exposed to gas molecules like NO2 and NH3 [@Kong2000]. This experiment demonstrated that CNTs can be used effectively in gas sensing applications, even without added functional groups. Two mechanisms have been proposed for the sensing of gases by pristine carbon nanotubes. The first involves charge transfer to the CNTs from adsorbed gas molecules, and the other involves gas-induced modification of the Schottky barrier at contacts between the semi-conducting CNTs and metal electrodes, as well as between semi-conducting and metallic CNTs [@Battie2011; @Boyd2014]. Boyd *et al.* found that the main interaction between NO$_2$ and the CNT network occurs through adsorption at CNT-CNT junctions, either due to doping by charge transfer from the CNT to the NO$_2$ or due to charge being carried by the NO$_2$ from one CNT to the next. Chen *et al.* [@Chen2019] found that a double exponential response is obtained when a FET with a CNT network channel was exposed to gases, and that the time constants of these exponentials were characteristic of gas type and FET construction. 

## Insect Odorant Receptor Biosensors

### Insect Odorant Receptors

### Biosensor Examples

##	Non-Specific Binding

### Overview {#sec-non-specific-binding}



###	Non-Specific Binding to Channels

###	Non-Specific Binding to Apparatus

#### Encapsulation {.unnumbered}

#### PDMS Well {.unnumbered}

#### Reference Electrode {.unnumbered}