---
keep-tex: true
format: pdf
---

# Fabrication of Carbon Nanotube Network and Graphene Field-Effect Transistors {#sec-fabrication}

This chapter discusses the fabrication processes for both the carbon nanotube network and graphene transistors. Experimental optimisation of the transducer element is critical for biosensor work, and large numbers of transducers were required for testing various biosensor functionalisation processes. Therefore, these processes were developed to rapidly fabricate devices with reproducible device characteristics appropriate for biosensing work. Also outlined in this chapter are the characterisation techniques taken to test the quality and reproducibility of these fabrication processes. 

The nitrogen ($\geq$ 99.99%) and oxygen (99.7%) used in fabrication work  was supplied by BOC Limited New Zealand. Deionised (DI) water was taken from a Synergy$^\circledR$ UV Water Purification System. The DI water had a measured conductivity of $(1.4\pm0.1)\textrm{ } \mu \textrm{S cm}^{-1}$, compared to tap water with a measured conductivity of $(7.8\pm0.2)\textrm{ } \mu \textrm{S cm}^{-1}$.

## Deposition of Carbon Nanotubes

4-inch $p$-type (B-doped) silicon wafers with either a 100 nm or 300 nm SiO$_2$ layer (WaferPro LLC) were used as the substrate for carbon nanotube network deposition. A 100 nm SiO$_2$ layer was the preferred option for the devices intended for backgated measurements. Before deposition of carbon nanotubes, the wafers were spin-coated with AZ$^\circledR$ 1518 photoresist, placed photoresist-side down onto a cleanroom wipe, fixed in place using vacuum suction, then cleaved into quarters using a diamond-tipped scribe tool. For fabrication performed before June 2023, the protective photoresist layer was then removed by soaking the quarter-wafers in acetone for 15 minutes, then rinsed with isopropyl alcohol (IPA) and dried with N2 gas. However, for complete removal of photoresist, we found it was necessary to flood expose the device with the Karl Suss Aligner for 1 min and then place it in AZ326 developer for 3 min, as discussed further in @sec-fluorescence-characterisation. 

Carbon nanotubes were deposited before alignment markers photolithography on all wafers fabricated between Aug 2021-Feb 2023, while devices fabricated before Aug 2021 and after Feb 2023 had alignment markers photolithography performed before the deposition of carbon nanotubes. The process order was first switched in Aug 2021 as this order led to faster processing times. However, the order was switched back in Feb 2023 to minimise the exposure of carbon nanotubes to photolithographic chemical processes.

### Solvent-Based

The solvent-based deposition process for the carbon nanotube network in the second fabrication protocol is as follows. 10 mg of 2-mercaptopyridine (99%, Sigma-Aldrich) was dissolved in 1 ml ethanol by sonication until clear. Quarter wafers were sonicated in acetone for 3 min, then exposed to O$_2$ plasma at 100 W for at least 2 min in a small plasma cleaner (Plasma Etch, Inc, PE-50 Compact Benchtop Plasma Cleaning System) or reactive ion etcher (Oxford Instruments, Plasmalab 80 Plus). The cleaned SiO$_2$/Si surface was then coated with 2-mercaptopyridine for 10 minutes, rinsed with ethanol to remove residual $2$-mercaptopyridine, and then nitrogen dried. Meanwhile, 5 $\mu$g of carbon nanotube bucky paper (NanoIntegris, IsoNanotubes S-99) was dispersed in 10 mL of dichlorobenzene (Sigma Aldrich) by ultrasonication until no particles were visible to the naked eye. During this time, the ultrasonic bath temperature was kept between 20 - 30 $^\circ$C or the buckypaper would not disperse successfully. The substrates were then placed into a dish with CNT-DCB suspension and left covered for 1 hour, dipped into ethanol for 10 min to remove excess solvent and any unattached carbon nanotube bundles, and then dried with nitrogen. 

### Surfactant-Based

Two different approaches were used to attach the surfactant-dispersed CNTs. In both approaches, the quarter wafers were rinsed with ultrapure deionised water (DI water), acetone and IPA before being placed into a reactive ion etcher (Oxford Instruments, Plasmalab 80 Plus) and exposed to O$_2$ plasma at 100 W for at least 2 min in a small plasma cleaner (Plasma Etch, Inc, PE-50 Compact Benchtop Plasma Cleaning System) or reactive ion etcher (Oxford Instruments, Plasmalab 80 Plus) to make the surface hydrophilic. 1 mL of poly-L-lysine (PLL) was immediately deposited onto each quarter wafer and left for 5 minutes. Then, the quarter wafers were rinsed for 30 s with DI water and dried with N$_2$ gas. This process allows for the surface adhesion of semiconducting single carbon nanotubes suspended in surfactant. 

#### Simple Dropcasting {.unnumbered}

2 mL of IsoNanotubes-S 90% or 99% solution (NanoIntegris) was decanted into a small bottle and sonicated for 5 s to break up bundles of CNTs. An even spread of 400 $\mu$L CNT solution was placed in the centre of the PLL-functionalised quarter wafer, covered and left for 10 minutes. The CNT solution was then rinsed off with DI water and IPA, and then the quarter wafer was dried with N$_2$ gas. Next, the quarter wafer was annealed in a vacuum oven at 150$^\circ$ C for 1 hour. This method would often lead to an inhomogeneous spread of CNTs across the quarter wafer surface, detailed further in section @sec-AFM-characterisation.

#### Steam-Assisted Method {.unnumbered}

2 mL of IsoNanotubes-S 90% or 99% solution (NanoIntegris) was decanted into a small bottle and burst-sonicated once (on then off again) to break up bundles of CNTs. 75 mL of 95$^\circ$ C water was then placed into a glass dish on a hotplate held at 95$^\circ$ C. After this, the PLL-functionalised quarter wafer was placed in the centre of an insulating surface on the same hotplate. The CNT dispersion was carefully spread across the surface of the wafer without spilling any over the wafer edges. The wafer on the insulating surface and glass dish were then left covered for 2 minutes to expose the wafer to steam from the glass dish. The use of an insulating surface meant that the wafer and CNT dispersion were not heated from below while exposed to steam. The CNT dispersion was then rinsed off the wafer with DI water, ethanol, acetone and IPA, and then the quarter wafer was dried with N$_2$ gas. As in the original method, the quarter wafer was then annealed in a vacuum oven at 150$^\circ$ C for 1 hour. This method gave an even spread of CNTs across the quarter wafer surface, leading to a greater consistency in performance between devices. Further details can be found in section @sec-AFM-characterisation.

##	Characterisation via Fluorescence Microscopy {#sec-fluorescence-characterisation}

##	Characterisation via Atomic Force Microscopy {#sec-AFM-characterisation}