project:
  type: book
  output-dir: docs

book:
  title: "Volatile Organic Compound Detection Using Insect Odorant-Receptor Functionalised Field-Effect Transistors"
  author: "Eddyn Oswald Perkins Treacher"
  date: today
  date-format: "MMM YYYY"
  chapters:
    - index.qmd
    # - 0-abstract.qmd
    # - 1-introduction.qmd
    # - 2-transistors.qmd
    # - 3-biosensors.qmd
    #- 4-fabrication.qmd
    - 5-pristine-characterisation.qmd
    # - 6-functionalisation-verification.qmd
    # - 7-functionalisation-testing.qmd
    # - 8-vapour-sensing.qmd
    # - 9-conclusions.qmd
    #    - acknowledgements.qmd         # uncomment this line to see acknowledgements in html (will appear twice in pdf)
  appendices:
    #- app1-photolithography.qmd
    - app2-FET-analysis-software.qmd
    #- app3-vapour-delivery-system.qmd
bibliography: references.bib
cite-method: biblatex
biblatexoptions:
  - citestyle = ieee
  - urldate = iso8601

mainfont: Latin Modern Roman
sansfont: Latin Modern Roman

execute:
  echo: false # change to false to hide code

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    keep-tex: true 
    toc: false
    papersize: a4
    header-includes: |
      \usepackage{titling}
      \setlength{\droptitle}{-2cm}
      \preauthor{
        \begin{center}
        \Large
        \vspace{10mm}
        by

        \vspace{20mm}
      }
      \postauthor{
        \end{center}
        \vfill
      }
      
      \predate{
        \begin{center}
        A thesis 
        submitted in fulfilment of the \\
        requirements of the degree of \\
        Doctor of Philosophy in Physics\\               % Degree
        School of Physical and Chemical Sciences\\          % Department
        Te Herenga Waka - Victoria University of Wellington\\                       % University 
        \vspace{5mm}
      }
      \postdate{
        \\
        \includegraphics[width=3in,height=1.5in]{figures/VUW-logo.png}\\
        \end{center}
        }
  docx:
    toc: false
    number-sections: false
    highlight-style: github
    cite-method: citeproc
    link-citations: true
    reference-section-title: "References"

editor: visual
