project:
  type: book
  output-dir: docs
  
book:
  title: "Volatile Organic Compound Detection Using Insect Odorant-Receptor Functionalised Field-Effect Transistors"
  author: "Eddyn Oswald Perkins Treacher"
  date: today
  date-format: "MMM YYYY"
  chapters:
    - index.qmd
    - 0-abstract.qmd
    - 1-introduction.qmd
    - 2-biosensors.qmd
    - 3-fabrication.qmd
    - 4-OR-functionalisation.qmd
    - 5-liquid-sensing.qmd
    - 6-vapour-sensing.qmd
    - 7-conclusions.qmd
    #    - acknowledgements.qmd         # uncomment this line to see acknowledgements in html (will appear twice in pfd)
    - references.qmd
  # appendices:
    # - app1-resources.qmd
    # - app2-tools.qmd

bibliography: references.bib

execute:
  echo: false # change to false to hide code

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    keep-tex: true 
    toc: false
    papersize: a4
    header-includes: |
      \usepackage{titling}
      \setlength{\droptitle}{-2cm}
      \preauthor{
        \begin{center}
        \Large
        \vspace{10mm}
        by

        \vspace{20mm}
      }
      \postauthor{
        \end{center}
        \vfill
      }
      
      \predate{
        \begin{center}
        A thesis 
        submitted in fulfilment of the \\
        requirements of the degree of \\
        Doctor of Philosophy in Physics\\               % Degree
        School of Physical and Chemical Sciences\\          % Department
        Te Herenga Waka - Victoria University of Wellington\\                       % University 
        \vspace{5mm}
      }
      \postdate{
        \\
        \includegraphics[width=3in,height=1.5in]{figures/VUW-logo.png}\\
        \end{center}
        }
        

       

editor: visual

