project:
  type: book
  output-dir: docs
book:
  title: "Developing an Insect Odorant Receptor Bioelectronic Nose for Vapour-Phase Detection"
  author: "Eddyn Oswald Perkins Treacher"
  date: today
  date-format: "MMM YYYY"
  chapters:
     - index.qmd
     - 2-transistors.qmd
     - 3-biosensors.qmd
     - 4-fabrication.qmd
     - 5-pristine-characterisation.qmd
     - 6-functionalisation-verification.qmd
     - 7-functionalisation-testing.qmd
     - 8-vapour-system.qmd
     - 9-vapour-sensing.qmd
     - 10-conclusions.qmd
  appendices:
    - app1-vapour-sensor-components.qmd
    - app2-FET-analysis-software.qmd
    - references.qmd
bibliography: references.bib
cite-method: biblatex
biblatexoptions:
  #- citestyle=numeric
  #- sorting=none  # Optional: to preserve the order of citations as they appear in the document
  - citestyle = ieee
  - urldate = iso8601
#mainfont: lmroman17-regular.otf
#sansfont: lmroman17-regular.otf
mainfont: Latin Modern Roman
sansfont: Latin Modern Roman
linestretch: 1.2
execute:
  echo: false # change to false to hide code
  show: false # change to false to hide code
format:
  #html:
    #theme: cosmo
  pdf:
    #include-in-header: header.tex
    documentclass: scrbook
    template-partials:
      - before-body.tex
      - toc.tex
      - biblio.tex
    keep-tex: true 
    toc: true
    toc-title: Table of Contents
    lot: true
    lof: true
    biblio-title: References
    papersize: a4
    prefer-html: true
    header-includes: |
      \usepackage{fancyhdr}
      \usepackage{textcomp}
      \usepackage{titling}
      \usepackage{pdflscape}
      \usepackage{rotating}
      \usepackage{geometry}
      \usepackage{setspace}
      \setlength{\droptitle}{-2cm}
      \preauthor{
        \begin{center}
        \Large
        \vspace{15mm}
        by
        \vspace{10mm}
        
      }
      \postauthor{
        \end{center}
        
      }

      \predate{
        \begin{spacing}{1.2}
        \begin{center}
        \vspace{22mm}
        
        A thesis \\
        submitted to the Victoria University of Wellington \\
        in partial fulfilment of the requirements for the  \\
        degree of Doctor of Philosophy\\               % Degree
        \vspace{24mm}
        Te Herenga Waka $-$ Victoria University of Wellington\\
      }
      \postdate{
        \\
        \includegraphics[width=3in,height=1.5in]{figures/VUW-logo.png}\\
        \end{center}
        \end{spacing}
        }

      \renewcommand{\topfraction}{.8}
      \renewcommand{\bottomfraction}{.7}
      \renewcommand{\textfraction}{.15}
      \renewcommand{\floatpagefraction}{.8}
      \setcounter{topnumber}{3}
      \setcounter{bottomnumber}{3}
      \setcounter{totalnumber}{4}

      \clubpenalty=9996
      \widowpenalty=9999

  docx:
    toc: false
    number-sections: false
    highlight-style: github
    cite-method: citeproc
    link-citations: true
    reference-section-title: "References"
    prefer-html: true
editor: source