project:
  type: book
  output-dir: docs
  
book:
  title: "Volatile Organic Compound Detection Using Insect Odorant-Receptor Functionalised Field-Effect Transistors"
  author: "Eddyn Oswald Perkins Treacher"
  date: today
  date-format: "dd MM YYYY"
  chapters:
    - index.qmd
    - 0-abstract.qmd
    - 1-introduction.qmd
    - 2-biosensors.qmd
    - 3-methods.qmd
    - 4-functionalisation.qmd
    - 5-liquid-sensing.qmd
    - 6-vapour-sensing.qmd
    - 7-conclusions.qmd
    #    - acknowledgements.qmd         # uncomment this line to see acknowledgements in html (will appear twice in pfd)
    - references.qmd
  # appendices:
    # - app1-resources.qmd
    # - app2-tools.qmd

bibliography: references.bib

execute:
  echo: false # change to false to hide code

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    keep-tex: true 
    toc: false
    papersize: a4
    header-includes: |
      \usepackage{titling}
      \setlength{\droptitle}{-2cm}
      \preauthor{
        \begin{center}
        \includegraphics[width=5in,height=4in]{figures/IMG_20210719_134928644.jpg}\\ % cover figure
        \Large
      }
      \postauthor{
        \end{center}
      }
      \predate{
        \begin{center}
        Doctor of Philosophy in Physics\\               % Degree
        Department of Physical and Chemical Sciences\\          % Department
        Te Herenga Waka - Victoria University of Wellington\\                       % University 
        \vspace{5mm}
      }
      \postdate{
        \\
        \includegraphics[width=1.5in,height=1.5in]{figures/UiB-emblem500px_gray.png}\\
        \end{center}
        \newpage
        \mbox{}
        \vfill
        Cover page\\
        }
    # \emph{Beckwithia glacialis} on Snøhetta.
        

       

editor: visual

