---
keep-tex: true
format: pdf
linestretch: 1.2
---

# Python Code for Data Analysis {.appendix}

The code used for general analysis of field-effect transistor devices in this thesis was written with Python 3.8.8. Contributors to the code used include Erica Cassie, Erica Happe, Marissa Dierkes and Leo Browning. The code is located on GitHub and the research group OneDrive, as well as being publicly available on Figshare [@Treacher2024].

## Atomic Force Microscope Histogram Analysis {#sec-histogram-analysis}

The purpose of this code is to analyse atomic force microscope (AFM) images of carbon nanotube networks in .xyz format (see @sec-afm-characterisation). It was originally designed by Erica Happe in Matlab, and adapted by Marissa Dierkes and myself for use in Python. The code imports the .xyz data and sorts it into bins 0.15 nm in size for processing. To perform skew-normal distribution fits, both *scipy.optimize.curve_fit* and *scipy.stats.skewnorm* modules are used in this code.

## Raman Spectroscopy Analysis {#sec-raman-analysis}

The purpose of this code is to analyse a series of Raman spectra taken at different points on a single film (see @sec-raman-characterisation). Data is imported in a series of tab-delimited text files, with the low wavenumber spectrum (100 cm$^{-1} - 650$ cm$^{-1}$) and high wavenumber spectrum (1300 cm$^{-1} - 1650$ cm$^{-1}$) imported in separate datafiles for each scan location.

## Field-Effect Transistor Analysis {#sec-field-effect-transistor-analysis}

The purpose of this code is to analyse electrical measurements taken of field-effect transistor (FET) devices. Electrical measurements were either taken from the Keysight 4156C Semiconductor Parameter Analyser, National Instruments NI-PXIe or Keysight B1500A Semiconductor Device Analyser as discussed in @sec-electrical-characterisation; the code is able to analyse data in .csv format taken from all three measurement setups. The main Python file in the code base consists of three related but independent modules: the first analyses and plots sensing data from the FET devices, the second analyses and plots transfer characteristics from channels across a device, and the third compares individual channel characteristics before and after a modification or after each individual modification in a series of modifications. The code base also features a separate config file and style sheet which govern the behaviour of the main code. The code base was designed collaboratively by myself and Erica Cassie over GitHub using the Sourcetree Git GUI.

## Vapour Delivery System Analysis {#sec-vapour-delivery-analysis}

The purpose of this code is to display electrical measurements taken of field-effect transistor devices inside the vapour delivery system chamber alongside data collected from the photoionisation detector and mass flow controllers. Electrical measurements were taken with the Keysight 4156C Semiconductor Parameter Analyser or Keysight B1500A Semiconductor Device Analyser, using the vapour sensing chamber chip carrier described in @sec-electrical-characterisation. Electrical data is imported from a .csv file, while photoionisation detector data is imported from a tab-delimited text file and mass flow controller data is imported from a .lvm file. 