# Vapour Delivery System

## Technical Notes



Two LabView Virtual Instruments (VIs) were adapted from pre-existing VIs for operating the mass flow controllers and monitoring vapour flow into the device chamber, as well as monitoring temperature and humidity in the vapour delivery system's manifold. These VIs were named ""  A third VI was developed in parallel which combined the first two Virtual Instruments, alongside allowing the sequence of values to control the mass flow controllers.

From Honours report:
"""
Figure 12 gives the right side of the front panel of the LabView VI sample with vapour.VI, which letsus preset an autonomously-performed vapour sensing sequence. Each row in each array module corresponds to a differennest step in this sequence. The 'howManySteps' module lets us set how many of these steps are performed. The 'Durations Array' module determines the length of time in seconds each step is performed over. The 'Carrier Flows Array' and 'Dilution Flows Array' modules let us set the carrier flow and dilution 
flow, respectively, in standard cubic centimetres per minute (sccm) through the gas rig at each step. The carrier flow pushes analyte vapour into the vapour-sensing device chamber, while dilution flow is used to modify the flow behaviour of the analyte vapour entering the chamber. The vapour sensing sequence as depicted in Figure 12 was used for all vapour sensing runs in this investigation. At the end of the sequence, the data collected about the vapour sensing process was saved as an .lvm file.
"""

## Future Improvements
