# Introduction

## Background

The "bioelectronic nose", an electronic transducer modified with elements of the animal olfactory system, has the potential to allow specific detection of airborne volatile compounds at concentrations as low as parts per trillion [@Glatz2011; @Kwon2015; @Dung2018; @Kim2022a]. The thin-film transistor (TFT), a type of field-effect transistor (FET), is a particularly portable, simple to use, small and robust option for the transducer component [@Kauffman2008; @Khan2020]. The thin films used in these transistors include carbon nanotube networks and graphene, low-dimensional nanomaterials which are both highly sensitive and biocompatible [@Shkodra2021]. The implications of successful development of such a portable and robust bioelectronic nose are significant. Applications could be found in high-importance fields such as biosecurity, medicine, environmental protection and food safety [@Dung2018; @Arakawa2019; @Yang2017; @Son2017]. For example, it has been demonstrated that it is possible to specifically detect invasive brown marmorated stinkbugs based on their volatile trace [@Moser2020]. A bioelectronic nose could potentially accomplish this biosecurity task far more cheaply and efficiently than trained sniffer dogs [@Lee2010; @Moon2020; @Terutsuki2020]. There has been rapid progress in the development of bioelectronic noses using carbon nanotube field-effect transistors (CNT FETs) and graphene field-effect transistors (GFETs) over the past 15-20 years [@Yoon2009; @Lee2010; @Yang2018].

Insect odorant receptors (iORs) enable simple invertebrates, such as the vinegar fruit fly *Drosophila melanogaster*, to distinguish between a huge number of specific volatile compounds [@Hallem2004; @Smart2008; @Wicher2008; @Munch2016; @Bohbot2020]. Within the past five years, a variety of *Drosophila melanogaster* iORs have been successfully coupled with highly sensitive low-dimensional thin-film transistors for specific detection of fruit-like odors in an aqueous environment [@Murugathas2019a; @Murugathas2020]. Insect odorant receptors have also been used for sensitive and selective volatile detection of volatile compounds in a lipid bilayer format [@Yamada2021]. In this thesis, the primary aim was to verify whether a bioelectronic nose capable of odorant detection in a vapour-phase environment could be constructed by coupling iORs with thin-film transistors. Alongside the future use of this technology in targeted sensor applications, development of a vapour-phase bioelectronic nose using iORs may give us a greater understanding of the mechanisms underlying insect olfaction [@Lee2010]. The transduction mechanism of nanomaterial-based iOR sensors is still unknown, and it is hoped this work sheds further light on the biological and electronic processes underpinning this mechanism [@Murugathas2020; @Khadka2019; @Cheema2021].

To answer the question of whether selective vapour-phase detection could be achieved using the architecture described above, it was first important to verify that each of the component parts of this highly integrated system functioned as expected and were mutually compatible. As the thin-film transistor is a relatively recent technology, the design and fabrication of these devices continues to evolve, and it was important to ensure that the methods used gave rise to devices of consistent quality which were sufficiently sensitive. Insect odorant receptor biofunctionalisation is also an emerging field; it was important to review and test existing functionalisation approaches, identifying their relative strengths and weaknesses for biosensor applications. Finally, to ensure that both functioning parts worked together once integrated, the functionalised transducer was tested in an aqueous environment to compare its sensitivity with previous research [@Murugathas2019a; @Murugathas2020]. A suitable vapour delivery system for testing the working sensors was developed in parallel, with reference sensors installed to compare their responses with the activity of the biosensor. Once this system was confirmed to behave in a controllable manner, the bioelectronic nose was tested in the vapour-phase environment.

## Thesis Outline

This thesis consists of ten chapters. The first three chapters, including this one, are background chapters introducing the general topics of this thesis. The fourth chapter is a methods chapter, describing device fabrication and characterisation in detail. The fifth, sixth and seventh chapters describe the results obtained when verifying the sensitivity of the novel biosensor in an aqueous environment, while the eighth and ninth chapters relate the results of testing the biosensing platform in a vapour-phase environment. The tenth chapter concludes the thesis and discusses possible next steps for future research.

**Chapter 2** gives a broad description of carbon nanotube and graphene field-effect transistors with a focus on their use in sensing applications. The chapter begins by looking at the general structure and properties of thin-film transistors, where key figures of merit such as transconductance, on-off ratio, gate current and hysteresis are described. The chemical compositions of graphene and carbon nanotube networks are discussed, as well as their conduction behaviour and unique sensing properties when integrated into a field-effect transistor as the thin-film element.

**Chapter 3** investigates previous odorant receptor-coupled thin-film field-effect transistors examined in the literature. First, the biological structure of odorant receptors and membrane formats for their protection *in vitro* are discussed. Details are then provided regarding the construction and operation of existing vertebrate odorant receptor biosensors. The structure and function of the insect odorant receptor is then contrasted with the vertebrate odorant receptor, and existing insect odorant receptor TFT biosensors in the literature are discussed. The chapter finishes with a brief discussion of non-specific binding and its role in hindering biosensor activity.

**Chapter 4** describes the fabrication of the CNT FET and GFET transducers used in this thesis and the characterisation techniques used to probe their behaviour. The chapter starts with an introduction to photolithography for thin-film transistor device fabrication. Various techniques are described for random deposition of carbon nanotube networks to act as channels for these thin-film transistors. Characterisation techniques described in this chapter include atomic force microscopy (AFM), fluorescence microscopy, Raman spectroscopy, and electrical characterisation with various semiconductor device analysers.

**Chapter 5** presents the results obtained from the use of characterisation techniques on the pristine GFETs and CNT FETs. Various carbon nanotube (CNT) network morphologies are displayed and analysed. The Raman spectra and electrical device parameters of these CNT network morphologies are then discussed, along with electrical parameters from graphene devices. The sensitivity of a dense CNT network morphology device is then verified in the aqueous phase.

**Chapter 6** explores the non-covalent functionalisation of GFETs and CNT FETs with various linker molecules for insect odorant receptor attachment. The linker molecules tested were 1-pyrenebutanoic acid N-hydroxysuccinimide ester (PBASE) and 1-pyrenebutyric acid (PBA) with 1-Ethyl-3-(3-dimethylaminopropyl)carbodiimide (EDC). Pyrene-NTA and pyrene-biotin were also investigated as other possible linker molecules. The quality of various functionalisation approaches was then explored with various fluorescent-tagged linker molecules and biomolecules. In this process, various potential obstacles to successful biosensor functionalisation were identified.

**Chapter 7** maps out progress made towards the creation of an insect odorant receptor functionalised thin-film biosensor which is responsive to target analyte in an aqueous environment. Two different approaches are described that gave rise to working aqueous-phase biosensors. The first functionalisation approach, which used PBASE in methanol, led to results that were difficult to reproduce. Possible factors underlying the unreliability of this method were then investigated. A second approach was then designed to avoid the undesirable influence of the confounding factors identified.

**Chapter 8** outlines the development of a vapour delivery system for characterisation of the insect odorant receptor functionalised TFT biosensors in a vapour-phase environment. The vapour delivery system was upgraded from an existing system to include new mass flow controllers (to have greater control of flow through the system) and off the shelf vapour sensors (to collect vapour flow data that could be used for comparison against biosensor activity). The chapter also describes the design and construction of an electronic interface to monitor and control the components of the vapour delivery system, as well as calibration of the mass flow controllers.

**Chapter 9** details the use of the vapour delivery system for testing the functionalised biosensors in the vapour phase. First, the flow behaviour of volatile organic vapours through the system was validated using onboard reference sensors. The response of a pristine carbon nanotube device to two volatile compounds was investigated and compared to signals from the reference sensors. Finally, a device functionalised using the second functionalisation approach from chapter 7 was tested in the vapour delivery system, and its responses to vapour were compared to those of a pristine device.

**Chapter 10** summarises the conclusions drawn from this work, and proposes various related studies which can be undertaken to continue the work described in this thesis.